######################################################
# ADD GLOBAL VARIABLES
######################################################
variables:
- template: 'variables/pipeline-variables.yaml' 

######################################################
# DISABLE PR TRIGGER
######################################################
pr: none

######################################################
# TRIGGER ON ANY FEATURE BRANCH
######################################################
trigger:
  batch: true
  branches:
    include:
    - feature/*

######################################################
# SET AGENT POOL OR IMAGE PREFERENCE
######################################################
pool: 
  vmImage: 'Ubuntu-latest'

######################################################
# SET RESOURCES AND REPO DEPENDANCIES
######################################################
resources:
- repo: self

######################################################
# SET STAGES
######################################################
stages:

#######################################################
#### BUILD APPLICATION
#######################################################
- stage: STAGE_BUILD  
  displayName: 'Build Stage'
  jobs:  

  - template: 'templates/template-build.yaml' 
    parameters:
      includeUnitTest: true
      includeSonarQube: true