######################################################
# ADD GLOBAL VARIABLES
######################################################
variables:
- template: 'variables/pipeline-variables.yaml' 

######################################################
# DISABLE PR TRIGGER
######################################################
pr: none

######################################################
# DISABLE AUTOMATIC BUILDS
######################################################
trigger: none

######################################################
# SET AGENT POOL OR IMAGE PREFERENCE
######################################################
pool: 
  vmImage: 'Ubuntu-latest'

######################################################
# SET RESOURCES AND REPO DEPENDANCIES
######################################################
resources:
- repo: self

######################################################
# SET STAGES
######################################################
stages:

#######################################################
#### STAGE - PROVISION TEST ENVIRONMENT
#######################################################
- stage: STAGE_PROVISION_TEST
  variables:
    - template: 'variables/pipeline-variables-tst.yml' 
  jobs:  

  - template: 'templates/template-infra.yaml' 
    parameters:
      azureSubscription: ${{ variables.azureSubscription }}